/* Generated By:JavaCC: Do not edit this line. SmiGrammarConstants.java */
package com.mod_snmp.SmiParser.Grammar;

public interface SmiGrammarConstants {

  int EOF = 0;
  int DEFINITIONS_T = 8;
  int ASSIGN_T = 9;
  int BEGIN_T = 10;
  int END_T = 11;
  int EXPORTS_T = 12;
  int IMPORTS_T = 13;
  int FROM_T = 14;
  int DOT_T = 15;
  int COMMA_T = 16;
  int LEFT_BRACE_T = 17;
  int RIGHT_BRACE_T = 18;
  int LEFT_PAREN_T = 19;
  int RIGHT_PAREN_T = 20;
  int LEFT_SQUARE_T = 21;
  int RIGHT_SQUARE_T = 22;
  int OR_T = 23;
  int SEMI_COLON_T = 24;
  int COLON_T = 25;
  int OBJECT_IDENTIFIER_T = 26;
  int OBJECT_TYPE_T = 27;
  int OBJECT_IDENTITY_T = 28;
  int OBJECT_GROUP_T = 29;
  int TEXTUAL_CONVENTION_T = 30;
  int NOTIFICATION_TYPE_T = 31;
  int NOTIFICATION_GROUP_T = 32;
  int MODULE_IDENTITY_T = 33;
  int MODULE_COMPLIANCE_T = 34;
  int AGENT_CAPABILITIES_T = 35;
  int TRAP_TYPE_T = 36;
  int LAST_UPDATED_T = 37;
  int ORGANIZATION_T = 38;
  int CONTACT_INFO_T = 39;
  int DESCRIPTION_T = 40;
  int REVISION_T = 41;
  int PRODUCT_RELEASE_T = 42;
  int MODULE_T = 43;
  int MANDATORY_GROUPS_T = 44;
  int GROUP_T = 45;
  int SUPPORTS_T = 46;
  int INCLUDE_T = 47;
  int VARIATION_T = 48;
  int CREATION_REQUIRES_T = 49;
  int NOTIFICATIONS_T = 50;
  int REFERENCE_T = 51;
  int SYNTAX_T = 52;
  int WRITE_SYNTAX_T = 53;
  int UNITS_T = 54;
  int INDEX_T = 55;
  int IMPLIED_T = 56;
  int AUGMENTS_T = 57;
  int DEFVAL_T = 58;
  int OBJECT_T = 59;
  int OBJECTS_T = 60;
  int DISPLAY_HINT_T = 61;
  int INCLUDES_T = 62;
  int ENTERPRISE_T = 63;
  int VARIABLES_T = 64;
  int STATUS_T = 65;
  int CURRENT_T = 66;
  int DEPRECATED_T = 67;
  int OBSOLETE_T = 68;
  int MANDATORY_T = 69;
  int ACCESS_T = 70;
  int MAX_ACCESS_T = 71;
  int MIN_ACCESS_T = 72;
  int NOT_ACCESSIBLE_T = 73;
  int ACCESSIBLE_FOR_NOTIFY_T = 74;
  int READ_ONLY_T = 75;
  int READ_WRITE_T = 76;
  int READ_CREATE_T = 77;
  int WRITE_ONLY_T = 78;
  int NOT_IMPLEMENTED_T = 79;
  int INTEGER_T = 80;
  int BITS_T = 81;
  int BIT_STRING_T = 82;
  int OCTET_STRING_T = 83;
  int SEQUENCE_OF_T = 84;
  int SEQUENCE_T = 85;
  int COUNTER32_T = 86;
  int COUNTER_T = 87;
  int GAUGE32_T = 88;
  int GAUGE_T = 89;
  int TIMETICKS_T = 90;
  int OPAQUE_T = 91;
  int IP_ADDRESS_T = 92;
  int NETWORK_ADDRESS_T = 93;
  int NSAP_ADDRESS_T = 94;
  int COUNTER64_T = 95;
  int UNSIGNED32_T = 96;
  int UINTEGER32_T = 97;
  int INTEGER32_T = 98;
  int INDEX_SYNTAX_T = 99;
  int APPLICATION_SYNTAX_T = 100;
  int OBJECT_SYNTAX_T = 101;
  int SIMPLE_SYNTAX_T = 102;
  int SIZE_T = 103;
  int UNTIL_T = 104;
  int MACRO_T = 105;
  int CHOICE_T = 106;
  int APPLICATION_T = 107;
  int UNIVERSAL_T = 108;
  int PRIVATE_T = 109;
  int EXPLICIT_T = 110;
  int IMPLICIT_T = 111;
  int BIN_NUMBER_T = 112;
  int HEX_NUMBER_T = 113;
  int DEC_NUMBER_T = 114;
  int UTC_TIME_T = 115;
  int TEXT_T = 116;
  int VALUE_IDENTIFIER_T = 117;
  int TYPE_IDENTIFIER_T = 118;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"--\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"DEFINITIONS\"",
    "\"::=\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"EXPORTS\"",
    "\"IMPORTS\"",
    "\"FROM\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\";\"",
    "\":\"",
    "<OBJECT_IDENTIFIER_T>",
    "\"OBJECT-TYPE\"",
    "\"OBJECT-IDENTITY\"",
    "\"OBJECT-GROUP\"",
    "\"TEXTUAL-CONVENTION\"",
    "\"NOTIFICATION-TYPE\"",
    "\"NOTIFICATION-GROUP\"",
    "\"MODULE-IDENTITY\"",
    "\"MODULE-COMPLIANCE\"",
    "\"AGENT-CAPABILITIES\"",
    "\"TRAP-TYPE\"",
    "\"LAST-UPDATED\"",
    "\"ORGANIZATION\"",
    "\"CONTACT-INFO\"",
    "\"DESCRIPTION\"",
    "\"REVISION\"",
    "\"PRODUCT-RELEASE\"",
    "\"MODULE\"",
    "\"MANDATORY-GROUPS\"",
    "\"GROUP\"",
    "\"SUPPORTS\"",
    "\"INCLUDE\"",
    "\"VARIATION\"",
    "\"CREATION-REQUIRES\"",
    "\"NOTIFICATIONS\"",
    "\"REFERENCE\"",
    "\"SYNTAX\"",
    "\"WRITE-SYNTAX\"",
    "\"UNITS\"",
    "\"INDEX\"",
    "\"IMPLIED\"",
    "\"AUGMENTS\"",
    "\"DEFVAL\"",
    "\"OBJECT\"",
    "\"OBJECTS\"",
    "\"DISPLAY-HINT\"",
    "\"INCLUDES\"",
    "\"ENTERPRISE\"",
    "\"VARIABLES\"",
    "\"STATUS\"",
    "\"current\"",
    "\"deprecated\"",
    "\"obsolete\"",
    "\"mandatory\"",
    "\"ACCESS\"",
    "\"MAX-ACCESS\"",
    "\"MIN-ACCESS\"",
    "\"not-accessible\"",
    "\"accessible-for-notify\"",
    "\"read-only\"",
    "\"read-write\"",
    "\"read-create\"",
    "\"write-only\"",
    "\"not-implemented\"",
    "\"INTEGER\"",
    "\"BITS\"",
    "<BIT_STRING_T>",
    "<OCTET_STRING_T>",
    "<SEQUENCE_OF_T>",
    "\"SEQUENCE\"",
    "\"Counter32\"",
    "\"Counter\"",
    "\"Gauge32\"",
    "\"Gauge\"",
    "\"TimeTicks\"",
    "\"Opaque\"",
    "\"IpAddress\"",
    "\"NetworkAddress\"",
    "\"NSapAddress\"",
    "\"Counter64\"",
    "\"Unsigned32\"",
    "\"UInteger32\"",
    "\"Integer32\"",
    "\"IndexSyntax\"",
    "\"ApplicationSyntax\"",
    "\"ObjectSyntax\"",
    "\"SimpleSyntax\"",
    "\"SIZE\"",
    "\"..\"",
    "\"MACRO\"",
    "\"CHOICE\"",
    "\"APPLICATION\"",
    "\"UNIVERSAL\"",
    "\"PRIVATE\"",
    "\"EXPLICIT\"",
    "\"IMPLICIT\"",
    "<BIN_NUMBER_T>",
    "<HEX_NUMBER_T>",
    "<DEC_NUMBER_T>",
    "<UTC_TIME_T>",
    "<TEXT_T>",
    "<VALUE_IDENTIFIER_T>",
    "<TYPE_IDENTIFIER_T>",
  };

}
