//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.SyntaxTree;

/**
 * Grammar production:
 * <PRE>
 * identifier -> TypeIdentifier()
 * -> &lt;ASSIGN_T&gt;
 * type -> Type() -- For specific information
 * </PRE>
 */
public class AssignmentType implements Assignment {
    private Node parent;
    public Identifier identifier;
    public Type type;

    public AssignmentType(Identifier n0, Type n1) {
        identifier = n0;
        if ( identifier != null ) identifier.setParent(this);
        type = n1;
        if ( type != null ) type.setParent(this);
    }
    public int line() {
        return identifier.line();
    }

    public void accept(com.mod_snmp.SmiParser.Visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.SmiParser.Visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

