//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.SyntaxTree;

/**
 * Grammar production:
 * <PRE>
 * -> &lt;LEFT_BRACE_T&gt;
 * -> ( ValueIdentifier() ( &lt;COMMA_T&gt; ValueIdentifier() )* )?
 * list -> ( ValueIdentifier() )*
 * -> &lt;RIGHT_BRACE_T&gt;
 * </PRE>
 *
 * Usage of grammar production:
 * </PRE>
 * list -> ( ValueIdentifier() )*
 * </PRE>
 */
public class BitValueList implements Node {
    private Node parent;
    public NodeList list;

    public BitValueList(NodeList n0) {
        list = n0;
        if ( list != null ) list.setParent(this);
    }
    public int line() {
        return list.line();
    }
    public void accept(com.mod_snmp.SmiParser.Visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.SmiParser.Visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

