//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.SyntaxTree;

/**
 * Grammar production:
 * <PRE>
 * -> &lt;CONTACT_INFO_T&gt;
 * nodeToken1 -> &lt;TEXT_T&gt;
 * </PRE>
 */
public class ContactInfoPart implements Node {
    private Node parent;
    public NodeToken nodeToken;

    public ContactInfoPart(NodeToken n0) {
        nodeToken = n0;
        if ( nodeToken != null ) nodeToken.setParent(this);
    }
    public int line() {
        return nodeToken.beginLine;
    }

    public void accept(com.mod_snmp.SmiParser.Visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.SmiParser.Visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

