//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.smiparser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> ( &lt;DEFVAL_T&gt; &lt;LEFT_BRACE_T&gt; DefValValue() &lt;RIGHT_BRACE_T&gt; )?
 * </PRE>
 */
public class DefValPart implements Node {
    private Node parent;
    public NodeOptional nodeOptional;

    public DefValPart(NodeOptional n0) {
        nodeOptional = n0;
        if ( nodeOptional != null ) nodeOptional.setParent(this);
    }
    public int line() {
        return nodeOptional.line();
    }
    public boolean present() {
         return nodeOptional.present();
    }
    public void accept(com.mod_snmp.smiparser.visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.smiparser.visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

