//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.SyntaxTree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;ENTERPRISE_T&gt;
 * identifier -> ValueIdentifier()
 * </PRE>
 */
public class EnterprisePart implements Node {
    private Node parent;
    public Identifier identifier;

    public EnterprisePart(Identifier n0) {
        identifier = n0;
        if ( identifier != null ) identifier.setParent(this);
    }
    public int line() {
        return identifier.line();
    }
    public void accept(com.mod_snmp.SmiParser.Visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.SmiParser.Visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

