//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.smiparser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * -> &lt;PRODUCT_RELEASE_T&gt;
 * nodeToken -> &lt;TEXT_T&gt;
 * </PRE>
 */
public class ProductReleasePart implements Node {
    private Node parent;
    public NodeToken nodeToken;

    public ProductReleasePart(NodeToken n0) {
        nodeToken = n0;
        if ( nodeToken != null ) nodeToken.setParent(this);
    }
    public int line() {
        return nodeToken.line();
    }
    public void accept(com.mod_snmp.smiparser.visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.smiparser.visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

