//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.smiparser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * key -> &lt;STATUS_T&gt;
 * value -> ( &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; )
 * </PRE>
 */
public class StatusPart implements Node {
    private Node parent;
    public NodeToken value;

    public StatusPart() {
        value = new NodeToken("");
        if ( value != null ) value.setParent(this);
    }
    public StatusPart(NodeToken n0) {
        value = n0;
        if ( value != null ) value.setParent(this);
    }
    public int line() {
        return value.line();
    }
    public void accept(com.mod_snmp.smiparser.visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.smiparser.visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

