//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.SyntaxTree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ &lt;UNITS_T&gt; &lt;TEXT_T&gt; ]
 * </PRE>
 */
public class UnitsPart implements Node {
    private Node parent;
    public NodeOptional nodeOptional;

    public UnitsPart(NodeOptional n0) {
        nodeOptional = n0;
        if ( nodeOptional != null ) nodeOptional.setParent(this);
    }
    public int line() {
        return nodeOptional.line();
    }
    public void accept(com.mod_snmp.SmiParser.Visitor.Visitor v) {
        v.visit(this);
    }
    public Object accept(com.mod_snmp.SmiParser.Visitor.ObjectVisitor v, Object argu) {
        return v.visit(this,argu);
    }
    public void setParent(Node n) { parent = n; }
    public Node getParent()       { return parent; }
}

