//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.SmiParser.Visitor;

import com.mod_snmp.SmiParser.SyntaxTree.*;

import java.util.Enumeration;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
    //
    // Auto class visitors--probably don't need to be overridden.
    //
    public void visit(NodeList n) {
        if ( n.present() ) {
            for ( Enumeration e = n.elements(); e.hasMoreElements(); )
                ((Node)e.nextElement()).accept(this);
        }
    }

    public void visit(NodeOptional n) {
        if ( n.present() )
            n.node.accept(this);
    }

    public void visit(NodeToken n) { }

    //
    // User-generated visitor methods below
    //

    /**
     * <PRE>
     * moduleIdentifier -> ModuleIdentifier()
     * -> &lt;DEFINITIONS_T&gt;
     * -> &lt;ASSIGN_T&gt;
     * -> &lt;BEGIN_T&gt;
     * exports_list -> [ &lt;EXPORTS_T&gt; ModuleExport() &lt;SEMI_COLON_T&gt; ]
     * import_module_list -> [ &lt;IMPORTS_T&gt; ( ModuleImport() )* &lt;SEMI_COLON_T&gt; ]
     * nodeList -> ( Assignment() )*
     * -> &lt;END_T&gt;
     * </PRE>
     */
    public void visit(ModuleDefinition n) {
        n.moduleIdentifier.accept(this);
        n.exports_list.accept(this);
        n.import_module_list.accept(this);
        n.assignmentList.accept(this);
    }

    /**
     * <PRE>
     * PredefinedMacro() -> (&lt;OBJECT_TYPE_T&gt;        | &lt;OBJECT_IDENTITY_T&gt;  
     *                     | &lt;OBJECT_GROUP_T&gt;       | &lt;TEXTUAL_CONVENTION_T&gt;
     *                     | &lt;NOTIFICATION_TYPE_T&gt;  | &lt;NOTIFICATION_GROUP_T&gt;
     *                     | &lt;MODULE_IDENTITY_T&gt;    | &lt;MODULE_COMPLIANCE_T&gt; 
     *                     | &lt;AGENT_CAPABILITIES_T&gt; | &lt;TRAP_TYPE_T&gt; )
     * SmiTypes() -> ( &lt;IP_ADDRESS_T&gt;   | &lt;NETWORK_ADDRESS_T&gt; 
     *               | &lt;NSAP_ADDRESS_T&gt; | &lt;COUNTER_T&gt;
     *               | &lt;COUNTER32_T&gt;    | &lt;COUNTER64_T&gt;
     *               | &lt;GAUGE_T&gt;        | &lt;GAUGE32_T&gt;
     *               | &lt;TIMETICKS_T&gt;    | &lt;OPAQUE_T&gt;
     *               | &lt;INTEGER_T&gt;      | &lt;INTEGER32_T&gt;
     *               | &lt;UINTEGER32_T&gt;   | &lt;UNSIGNED32_T&gt; )
     * Symbol() -> ( TypeIdentifier() | ValueIdentifier()
     *       | SmiTypes() | PredefinedMacro() )
     *
     * symbolList -> Symbol() (&lt;COMMA&gt; Symbol() )*
     * -> &lt;FROM_T&gt;
     * moduleIdentifier -> ModuleIdentifier()
     * </PRE>
     */
    public void visit(ModuleImport n) {
        n.symbolList.accept(this);
        n.moduleIdentifier.accept(this);
    }

    /**
     * <PRE>
     * nodeChoice -> TypeIdentifier() &lt;ASSIGN_T&gt; Type()
     * </PRE>
     */      
    public void visit(AssignmentType n) {
        n.identifier.accept(this);
        n.type.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;SEQUENCE_T&gt;
     *    &lt;L_BRACE_T&gt;
     *    ValueType() ( &lt;COMMA_T&gt; ValueType() )*
     *    &lt;R_BRACE_T&gt;
     * vtList -> ( ValueType() )*
     * </PRE>
     */
    public void visit(TypeSequence n) {
        n.vtList.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;TEXTUAL_CONVENTION_T&gt;
     * displayhint -> DisplayHintPart();             
     * status -> StatusPart();
     * description -> DescriptionPart(); 
     * reference -> ReferencePart();   
     * syntax -> SyntaxPart();
     * </PRE>
     */
    public void visit(TypeTextualConvention n) {
        n.displayhint.accept(this);
        n.status.accept(this);
        n.description.accept(this);
        n.reference.accept(this);
        n.syntax.accept(this);
    }

    /**
     * <PRE>
     * ->  &lt;CHOICE_T&gt;
     * choice ->  ChoiceValue()
     * </PRE>
     */
    public void visit(TypeChoice n) {
        n.vtList.accept(this);
    }

    /**         
     * <PRE>
     * -> [        
     *     -> &lt;LEFT_SQUARE_T&gt;       
     *     sort -> &lt;APPLICATION_T&gt; | &lt;UNIVERSAL_T&gt; | &lt;PRIVATE_T&gt;  
     *     number -> &lt;DEC_NUMBER_T&gt;       
     *     -> &lt;RIGHT_SQUARE_T&gt;       
     *     kind -> [ &lt;EXPLICIT_T&gt; | &lt;IMPLICIT_T&gt; ]       
     *     ]       
     * type -> Types() | Asn1Types()
     * </PRE>   
     */     
    public void visit(TypeTag n) { 
        if (n.present()) {
            n.sort.accept(this);
            n.number.accept(this);
            n.kind.accept(this);
        }
        n.type.accept(this);
    }           

    /**
     * <PRE>
     * identifier -> PredefinedMacros()  smi_defined == true
     *               |
     *               TypeIdentifier()    smi_defined == false
     * -> &lt;MACRO_T&gt;
     * -> &lt;ASSIGN_T&gt;
     * -> &lt;BEGIN_T&gt;
     * macro -> MacroBody()      
     * -> &lt;END_T&gt;
     * </PRE>
     */
    public void visit(AssignmentMacro n) {
        n.identifier.accept(this);
        n.macro.accept(this);
    }

    /**
     * <PRE>
     * identifier -> ValueIdentifier()
     * info -> ObjectInfo()
     * -> &lt;ASSIGN_T&gt;
     * assignedValue -> AssignedValue()
     * </PRE>
     */
    public void visit(AssignmentObject n) {
        n.identifier.accept(this);
        n.info.accept(this);
        n.assignedValue.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;OBJECT_IDENTIFIER_T&gt;
     * </PRE>
     */
    public void visit(ObjectInfoObjectIdentifier n) {
    }

    /**
     * <PRE>
     * -> Arbitrary not parsed stuff
     * </PRE>
     */
    public void visit(MacroBody n) {
    }

    /**
     * <PRE>
     * -> &lt;OBJECT_TYPE_T&gt;
     * syntaxPart -> SyntaxPart()
     * unitsPart -> UnitsPart()
     * max_access -> AccessPart()
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * indexPart -> IndexPart()
     * defValPart -> DefValPart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectType n) {
        n.syntaxPart.accept(this);
        n.unitsPart.accept(this);
        n.max_access.accept(this);
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
        n.indexPart.accept(this);
        n.defValPart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;MODULE_IDENTITY_T&gt;
     * lastUpdatedPart -> LastUpdatedPart()
     * organizationPart -> OrganizationPart()
     * contactInfoPart -> ContactInfoPart()
     * descriptionPart -> DescriptionPart()
     * revisions -> RevisionPart()
     * </PRE>
     */
    public void visit(ObjectInfoModuleIdentity n) {
        n.lastUpdatedPart.accept(this);
        n.organizationPart.accept(this);
        n.contactInfoPart.accept(this);
        n.descriptionPart.accept(this);
        n.revisions.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;OBJECT_IDENTITY_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectIdentity n) {
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;OBJECT_GROUP_T&gt;
     * objectsPart -> ObjectsPart()
     *             -> [ &lt;OBJECTS_T&gt; &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt; ]  
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectGroup n) {
        n.objectsPart.accept(this);
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;NOTIFICATION_TYPE_T&gt;
     * objectsPart -> ObjectsPart()
     *             -> [ &lt;OBJECTS_T&gt; &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt; ]  
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoNotificationType n) {
        n.objectsPart.accept(this);
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;NOTIFICATION_GROUP_T&gt;
     * notifications -> NotificationPart()
     *               -> &lt;NOTIFICATIONS_T&gt;
     *                  &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoNotificationGroup n) {
        n.notifications.accept(this);
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;MODULE_COMPLIANCE_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * moduleCompliancePart -> ( &lt;MODULE_T&gt; [ ModuleIdentifier() ]
     *                           [ MandatoryPart() ]
     *                           ( CompliancePart() )*
     *                          )+ 
     * </PRE>
     */
    public void visit(ObjectInfoModuleCompliance n) {
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
        n.moduleCompliancePart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;AGENT_CAPABILITIES_T&gt;
     * productReleasePart -> ProductReleasePart()
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * moduleCapabilitiesPart -> ( ModuleCapability() )*
     * </PRE>
     */
    public void visit(ObjectInfoAgentCapabilities n) {
        n.productReleasePart.accept(this);
        n.statusPart.accept(this);
        n.descriptionPart.accept(this);
        n.referencePart.accept(this);
        n.moduleCapabilitiesPart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;TRAP_TYPE_T&gt;
     * enterprisePart -> EnterprisePart()
     * variablesPart -> VariablesPart()
     *               -> [ &lt;VARIABLES_T&gt;
     *                    &lt;LEFT_BRACE_T&gt;
     *                    ObjectList()
     *                    &lt;RIGHT_BRACE_T&gt; ]
     * descriptionPart -> DescriptionPart()
     * number -> NumericValue()
     * </PRE>
     */
    public void visit(ObjectInfoTrapType n) {
        n.enterprisePart.accept(this);
        n.variablesPart.accept(this);
        n.descriptionPart.accept(this);
        n.number.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     * nodeList -> &lt;REVISION_T&gt; &lt;UTC_TIME_T&gt; DescriptionPart()
     * </PRE>
     * Syntaxtree :
     * <PRE>
     * time -> &lt;UTC_TIME_T&gt;
     * descr -> DescriptionPart()
     * </PRE>
     */
    public void visit(Revision n) {
        n.time.accept(this);
        n.descr.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;STATUS_T&gt;
     * nodeChoice -> ( &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; )
     * </PRE>
     */
    public void visit(StatusPart n) {
        n.value.accept(this);
    }

    /**
     * <PRE>
     * nodeChoice -> ( &lt;ACCESS_T&gt; | &lt;MAX_ACCESS_T&gt; | &lt;MIN_ACCESS_T&gt; )
     * nodeChoice1 -> ( &lt;NOT_ACCESSIBLE_T&gt; | &lt;ACCESSIBLE_FOR_NOTIFY_T&gt; | &lt;READ_ONLY_T&gt; | &lt;READ_WRITE_T&gt; | &lt;READ_CREATE_T&gt; | &lt;WRITE_ONLY_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; )
     * </PRE>
     */
    public void visit(AccessPart n) {
        n.key.accept(this);
        n.value.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;MODULE_T&gt;
     *    [ ModuleIdentifier() ]
     *    [ &lt;MANDATORY_GROUPS_T&gt;
     *      &lt;LEFT_BRACE_T&gt;
     *      ObjectList()
     *      &lt;RIGHT_BRACE_T&gt;
     *    ]
     *   ( CompliancePart() )*
     * </PRE>
     * syntax class variables:
     * <PRE>
     * module_id -> [ ModuleIdentifier() ]
     * mandatory_part -> [ ObjectList() ]
     * compliance_part -> ( CompliancePart() )*
     * </PRE>
     */
    public void visit(ModuleCompliance n) {
        n.module_id.accept(this);
        n.mandatory_part.accept(this);
        n.compliance_part.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     *  -> &lt;SUPPORTS_T&gt;
     * module_id -> ModuleIdentifier()
     * -> &lt;INCLUDES_T&gt;
     * -> &lt;LEFT_BRACE_T&gt;
     * object_list -> ObjectList()
     * -> &lt;RIGHT_BRACE_T&gt;
     * variation_part -> ( VariationPart() )*   
     * </PRE>
     */
    public void visit(ModuleCapability n) {
        n.module_id.accept(this);  
        n.object_list.accept(this);
        n.variation_part.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;VARIATION_T&gt;
     * identifier -> ValueIdentifier()
     * syntaxPart -> SyntaxPart()
     * write_syntax -> [ &lt;WRITE_SYNTAX_T&gt; Types() ]
     * access -> [ AccessPart() ]
     * creation_requires -> [ &lt;CREATION_REQUIRES_T&gt; &lt;LEFT_BRACE_T&gt; ObjectList() &lt;RIGHT_BRACE_T&gt; ]
     * defValPart -> DefValPart()
     * descriptionPart -> DescriptionPart()
     * </PRE>
     */
    public void visit(VariationPart n) {
        n.identifier.accept(this);
        n.syntaxPart.accept(this);
        n.write_syntax.accept(this);
        n.access.accept(this);
        n.creation_requires.accept(this);
        n.defValPart.accept(this);
        n.descriptionPart.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;SYNTAX_T&gt;
     * type -> Types()
     * </PRE>
     */
    public void visit(SyntaxPart n) {
        n.type.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;WRITE_SYNTAX_T&gt; Types()
     * type -> Types()
     * </PRE>
     */
    public void visit(WriteSyntaxPart n) {
        n.type.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;GROUP_T&gt; ValueIdentifier() DescriptionPart()
     * identifier -> ValueIdentifier()
     * description -> DescriptionPart()
     * </PRE>
     */
    public void visit(ComplianceGroup n) {
        n.identifier.accept(this);
        n.description.accept(this);
    }
     
    /**
     * <PRE>
     * -> &lt;OBJECT_T&gt; ValueIdentifier()
     *       [ SyntaxPart() ]
     *       [ WriteSyntaxPart() ]
     *       [ AccessPart() ]
     *       DescriptionPart()
     * identifier -> ValueIdentifier()
     * syntax -> [ SyntaxPart() ]
     * write_syntax -> [ WriteSyntaxPart() ]
     * access -> [ AccessPart() ]
     * description -> DescriptionPart()
     * </PRE>
     */
    public void visit(ComplianceObject n) {
        n.identifier.accept(this);
        n.syntax.accept(this);
        n.write_syntax.accept(this);
        n.min_access.accept(this);
        n.description.accept(this);
    }

    /**
     * <PRE>
     * nodeChoice -> &lt;SEQUENCE_OF_T&gt; TypeIdentifier()
     *       | &lt;INTEGER_T&gt; [ IntegerRestriction() ]
     *       | &lt;INTEGER32_T&gt; [ IntegerRestriction() ]
     *       | &lt;UINTEGER32_T&gt; [ IntegerRestriction() ]
     *       | &lt;UNSIGNED32_T&gt; [ IntegerRestriction() ]
     *       | &lt;BITS_T&gt; [ RestrictionNamedNumberList() ]
     *       | &lt;BIT_STRING_T&gt; [ RestrictionNamedNumberList() ]
     *       | &lt;OCTET_STRING_T&gt; [ RestrictionSize() ]
     *       | &lt;OBJECT_IDENTIFIER_T&gt;
     *       | &lt;COUNTER_T&gt;
     *       | &lt;COUNTER32_T&gt;
     *       | &lt;COUNTER64_T&gt;
     *       | &lt;GAUGE_T&gt; [ IntegerRestriction() ]
     *       | &lt;GAUGE32_T&gt; [ IntegerRestriction() ]
     *       | &lt;TIMETICKS_T&gt;
     *       | &lt;OPAQUE_T&gt; [ RestrictionSize() ]
     *       | &lt;NSAP_ADDRESS_T&gt;
     *       | &lt;IP_ADDRESS_T&gt;
     *       | &lt;NETWORK_ADDRESS_T&gt;
     * </PRE>
     */
    public void visit(TypeSmi n) {
        n.base.accept(this);
        n.restriction.accept(this);
    }

    /**
     * <PRE>
     * identifier -> TypeIdentifier()
     * restriction -> [ Restriction() ]
     * </PRE>
     */
    public void visit(TypeIdentifier n) {
        n.identifier.accept(this);
        n.restriction.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;SEQUENCE_OF_T&gt;
     * identifier -> TypeIdentifier()
     * </PRE>
     */
    public void visit(TypeSequenceOf n) {
        n.identifier.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;LEFT_PAREN_T&gt;
     * range -> Range()
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(RestrictionRange n) {
        n.range.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;LEFT_PAREN_T&gt;
     * -> &lt;SIZE_T&gt;
     * -> &lt;LEFT_PAREN_T&gt;
     * range -> Range()
     * -> &lt;RIGHT_PAREN_T&gt;
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(RestrictionSize n) {
        n.range.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;LEFT_BRACE_T&gt;
     * list -> NamedNumber() ( &lt;COMMA_T&gt; NamedNumber() )*
     * -> &lt;RIGHT_BRACE_T&gt;
     * </PRE>
     */
    public void visit(RestrictionNamedNumberList n) {
        n.list.accept(this);
    }

    /**
     * <PRE>
     * list-> RangeItem() ( &lt;OR_T&gt; RangeItem() )*                
     * </PRE>
     */
    public void visit(RangeList n) {
        n.list.accept(this);
    } 
    
    /**
     * <PRE>
     * -> NumericValue()
     *    [ &lt;UNTIL_T&gt; NumericValue() ]
     * begin -> NumericValue()                                  
     * end -> NumericValue() -- NodeOptional --
     * </PRE>
     */
    public void visit(RangeItem n) {
        n.begin.accept(this);
        n.end.accept(this);
    }

    /**
     * <PRE>
     * identifier -> ValueIdentifier()
     * -> &lt;LEFT_PAREN_T&gt;
     * number -> NumericValue()
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(NamedNumber n) {
        n.name.accept(this);
        n.number.accept(this);
    }

    /**
     * <PRE>
     * nodeChoice -> ( ModuleIdentifier() &lt;DOT_T&gt; &lt;TYPE_IDENTIFIER_T&gt; | &lt;TYPE_IDENTIFIER_T&gt; )
     * nodeChoice -> ( ModuleIdentifier() &lt;DOT_T&gt; ( &lt;VALUE_IDENTIFIER_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; | &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; ) | ( &lt;VALUE_IDENTIFIER_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; | &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; ) )
     * </PRE>
     */
    public void visit(Identifier n) {
        if (n.module_identifier != null) {
            n.module_identifier.accept(this);
        }
        n.identifier.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;TYPE_IDENTIFIER_T&gt;
     * </PRE>
     */
    public void visit(ModuleIdentifier n) {
        n.nodeToken.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;AUGMENTS_T&gt;
     * -> &lt;LEFT_BRACE_T&gt;
     * identifier -> Identifier()
     * -> &lt;RIGHT_BRACE_T&gt; )           
     * </PRE>
     */
    public void visit(IndexAugments n) {
        n.identifier.accept(this);
    }

    /** 
     * Grammar production:
     * <PRE>
     * -> &lt;IMPLIED_T&gt;
     * identifier -> Identifier()
     * </PRE>
     */
    public void visit(Index n) {
        n.identifier.accept(this);
    }


    /**
     * <PRE>
     * list -> Index() ( &lt;COMMA_T&gt; Index() )*
     * </PRE>
     */
    public void visit(IndexList n) {
        n.list.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;LEFT_BRACE_T&gt;
     * oidValue -> OidValue() ( OidValue() )+
     * -> &lt;RIGHT_BRACE_T&gt;
     * </PRE>
     */
    public void visit(AssignedValue n) {
        n.oidValue.accept(this);
    }

    /**
     * <PRE>
     * nodeChoice -> ValueIdentifier() [ &lt;LEFT_PAREN_T&gt; NumericValue() &lt;RIGHT_PAREN_T&gt; ]
     *       | NumericValue()
     * </PRE>
     */
    public void visit(OidValue n) {
        if (n.hasName()) {
            n.name.accept(this);
            if (n.hasNumber()) {
                n.numval.accept(this);
            }
        } else if (n.hasNumber()) {
            n.numval.accept(this);
        }
    }

    /**
     * <PRE>
     * nodeChoice -> &lt;DEC_NUMBER_T&gt;
     *       | &lt;BIN_NUMBER_T&gt;
     *       | &lt;HEX_NUMBER_T&gt;
     * </PRE>
     */
    public void visit(NumericValue n) {
        n.value.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;DESCRIPTION_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(DescriptionPart n) {
        n.descr.accept(this);
    }

    /**
     * <PRE>
     * nodeOptional -> [ &lt;REFERENCE_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(ReferencePart n) {
        n.nodeOptional.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;CONTACT_INFO_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(ContactInfoPart n) {
        n.nodeToken.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;ORGANIZATION_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(OrganizationPart n) {
        n.nodeToken.accept(this);
    }

    /**
     * <PRE>
     * value -> ( &lt;DEFVAL_T&gt; &lt;LEFT_BRACE_T&gt;
     *               (  NumericValue()
     *               | ValueIdentifier()
     *               | &lt;TEXT_T&gt;
     *               | BitValueList()
     *               | AssignedValue()
     *               )
     *            &lt;RIGHT_BRACE_T&gt; )?
     * </PRE>
     */
    public void visit(DefValPart n) {
        n.nodeOptional.accept(this);
    }

    /**
     * <PRE>
     * list -> ( ValueIdentifier() )*
     * 
     * </PRE>
     */
    public void visit(BitValueList n) {
        n.list.accept(this);
    }

    /**
     * <PRE>
     * nodeOptional -> [ &lt;DISPLAY_HINT_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(DisplayHintPart n) {
        if (n.present()) {
            n.display_hint.accept(this);
        }
    }

    /**
     * <PRE>
     * -> &lt;LAST_UPDATED_T&gt;
     * nodeToken1 -> &lt;UTC_TIME_T&gt;
     * </PRE>
     */
    public void visit(LastUpdatedPart n) {
        n.nodeToken.accept(this);
    }

    /**
     * <PRE>
     * nodeOptional -> [ &lt;UNITS_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(UnitsPart n) {
        n.nodeOptional.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;PRODUCT_RELEASE_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(ProductReleasePart n) {
        n.nodeToken.accept(this);
    }

    /**
     * <PRE>
     * -> &lt;ENTERPRISE_T&gt;
     * identifier -> ValueIdentifier()
     * </PRE>
     */
    public void visit(EnterprisePart n) {
        n.identifier.accept(this);
    }

    /**
     * Grammar production:
     * <PRE>
     * identifier -> ValueIdentifier()
     * type -> Types()
     * </PRE>
     */
    public void visit(ValueType n) {
        n.identifier.accept(this);
        n.type.accept(this);
    }

}
