//
// Generated by JTB 1.2.2++
//

package com.mod_snmp.smiparser.visitor;

import com.mod_snmp.smiparser.syntaxtree.*;

/**
 * All void visitors must implement this interface.
 */
public interface Visitor {
   //
   // void Auto class visitors
   //
   public void visit(NodeList n);
   public void visit(NodeOptional n);
   public void visit(NodeToken n);

    //
    // User-generated visitor methods below
    //

    /**
     * <PRE>
     * moduleIdentifier -> ModuleIdentifier()
     * -> &lt;DEFINITIONS_T&gt;
     * -> &lt;ASSIGN_T&gt;
     * -> &lt;BEGIN_T&gt;
     * exports_list -> [ &lt;EXPORTS_T&gt; ModuleExport() &lt;SEMI_COLON_T&gt; ]
     * import_module_list -> [ &lt;IMPORTS_T&gt; ( ModuleImport() )* &lt;SEMI_COLON_T&gt; ]
     * assignmentList -> ( Assignment() )*
     * -> &lt;END_T&gt;
     * </PRE>
     */
    public void visit(ModuleDefinition n);

    /**
     * <PRE>
     * PredefinedMacro() -> (&lt;OBJECT_TYPE_T&gt;        | &lt;OBJECT_IDENTITY_T&gt;
     *                     | &lt;OBJECT_GROUP_T&gt;       | &lt;TEXTUAL_CONVENTION_T&gt;
     *                     | &lt;NOTIFICATION_TYPE_T&gt;  | &lt;NOTIFICATION_GROUP_T&gt;
     *                     | &lt;MODULE_IDENTITY_T&gt;    | &lt;MODULE_COMPLIANCE_T&gt;
     *                     | &lt;AGENT_CAPABILITIES_T&gt; | &lt;TRAP_TYPE_T&gt; )
     * SmiTypes() -> ( &lt;IP_ADDRESS_T&gt;   | &lt;NETWORK_ADDRESS_T&gt;      
     *               | &lt;NSAP_ADDRESS_T&gt; | &lt;COUNTER_T&gt;               
     *               | &lt;COUNTER32_T&gt;    | &lt;COUNTER64_T&gt;     
     *               | &lt;GAUGE_T&gt;        | &lt;GAUGE32_T&gt; 
     *               | &lt;TIMETICKS_T&gt;    | &lt;OPAQUE_T&gt;     
     *               | &lt;INTEGER_T&gt;      | &lt;INTEGER32_T&gt;   
     *               | &lt;UINTEGER32_T&gt;   | &lt;UNSIGNED32_T&gt; )      
     * Symbol() -> ( TypeIdentifier() | ValueIdentifier()      
     *       | SmiTypes() | PredefinedMacro() )      
     *
     * symbolList -> Symbol() (&lt;COMMA&gt; Symbol() )*
     * -> &lt;FROM_T&gt;
     * moduleIdentifier -> ModuleIdentifier()
     * </PRE>
     */
    public void visit(ModuleImport n);

    /**
     * <PRE>
     * nodeChoice -> TypeIdentifier() &lt;ASSIGN_T&gt; Types()
     *       | TypeIdentifier() &lt;ASSIGN_T&gt; &lt;TEXTUAL_CONVENTION_T&gt; DisplayHintPart() StatusPart() DescriptionPart() ReferencePart() SyntaxPart()
     *       | PredefinedMacro() &lt;MACRO_T&gt; &lt;ASSIGN_T&gt; &lt;BEGIN_T&gt; MacroBody() &lt;END_T&gt;
     *       | TypeIdentifier() &lt;MACRO_T&gt; &lt;ASSIGN_T&gt; &lt;BEGIN_T&gt; MacroBody() &lt;END_T&gt;
     *       | TypeIdentifier() &lt;ASSIGN_T&gt; &lt;CHOICE_T&gt; TypeChoice()
     *       | SmiTypes() &lt;ASSIGN_T&gt; &lt;CHOICE_T&gt; TypeChoice()
     *       | SmiTypes() &lt;ASSIGN_T&gt; Tag() Types()
     * </PRE>
     */
    public void visit(AssignmentType n);

    /**      
     * Grammar production:
     * <PRE> 
     * -> &lt;SEQUENCE_T&gt;
     *    &lt;L_BRACE_T&gt;
     *    ValueType() ( &lt;COMMA_T&gt; ValueType() )* 
     *    &lt;R_BRACE_T&gt;
     * vtList -> ( ValueType() )*
     * </PRE>
     */
    public void visit(TypeSequence n);

    /**
     * <PRE>
     * -> &lt;TEXTUAL_CONVENTION_T&gt;
     * displayhint -> DisplayHintPart();
     * status -> StatusPart();
     * description -> DescriptionPart();
     * reference -> ReferencePart();
     * syntax -> SyntaxPart();
     * </PRE>
     */ 
    public void visit(TypeTextualConvention n);

    /**
     * <PRE> 
     * ->  &lt;CHOICE_T&gt;
     * choice ->  TypeChoice()
     * </PRE>
     */
    public void visit(TypeChoice n);

    /**     
     * <PRE>
     * -> [
     *     -> &lt;LEFT_SQUARE_T&gt;
     *     sort -> &lt;APPLICATION_T&gt; | &lt;UNIVERSAL_T&gt; | &lt;PRIVATE_T&gt; 
     *     number -> &lt;DEC_NUMBER_T&gt;
     *     -> &lt;RIGHT_SQUARE_T&gt;
     *     kind -> [ &lt;EXPLICIT_T&gt; | &lt;IMPLICIT_T&gt; ]
     *     ]
     * type -> Types() | Asn1Types()
     * </PRE>
     */
    public void visit(TypeTag n);
     
    /**
     * <PRE>
     * identifier -> PredefinedMacros()  smi_defined == true
     *               |
     *               TypeIdentifier()    smi_defined == false
     * -> &lt;MACRO_T&gt;
     * -> &lt;ASSIGN_T&gt;
     * -> &lt;BEGIN_T&gt;
     * macro -> MacroBody()
     * -> &lt;END_T&gt;
     * </PRE>
     */
    public void visit(AssignmentMacro n);

    /**
     * <PRE>
     * identifier -> ValueIdentifier()   
     * info -> ObjectInfo()
     * -> &lt;ASSIGN_T&gt;
     * assignedValue -> AssignedValue()
     * </PRE>
     */
    public void visit(AssignmentObject n);

    /**
     * <PRE>
     * -> &lt;OBJECT_IDENTIFIER_T&gt;
     * </PRE>
     */
    public void visit(ObjectInfoObjectIdentifier n);

    /**
     * <PRE>
     * -> Arbitrary not parsed stuff
     * </PRE>
     */
    public void visit(MacroBody n);

    /**
     * <PRE>
     * -> &lt;OBJECT_TYPE_T&gt;
     * syntaxPart -> SyntaxPart()
     * unitsPart -> UnitsPart()
     * accessPart -> AccessPart()
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * indexPart -> IndexPart()
     * defValPart -> DefValPart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectType n);

    /**
     * <PRE>
     * -> &lt;MODULE_IDENTITY_T&gt;
     * lastUpdatedPart -> LastUpdatedPart()
     * organizationPart -> OrganizationPart()
     * contactInfoPart -> ContactInfoPart()
     * descriptionPart -> DescriptionPart()
     * revisions -> RevisionPart()
     * </PRE>
     */
    public void visit(ObjectInfoModuleIdentity n);

    /**
     * <PRE>
     * -> &lt;OBJECT_IDENTITY_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectIdentity n);

    /**
     * <PRE>
     * -> &lt;OBJECT_GROUP_T&gt;
     * objectsPart -> ObjectsPart()
     *             -> [ &lt;OBJECTS_T&gt; &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt; ]
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoObjectGroup n);

    /**
     * <PRE>
     * -> &lt;NOTIFICATION_TYPE_T&gt;
     * objectsPart -> ObjectsPart()
     *             -> [ &lt;OBJECTS_T&gt; &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt; ]
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoNotificationType n);

    /**
     * <PRE>
     * -> &lt;NOTIFICATION_GROUP_T&gt;
     * notifications -> NotificationPart()
     * notifications -> NotificationPart()
     *               -> &lt;NOTIFICATIONS_T&gt;
     *                  &lt;LEFT_BRACE_T&gt;
     *                  ObjectList()
     *                  &lt;RIGHT_BRACE_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * </PRE>
     */
    public void visit(ObjectInfoNotificationGroup n);

    /**
     * <PRE>
     * -> &lt;MODULE_COMPLIANCE_T&gt;
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * moduleCompliancePart -> ( &lt;MODULE_T&gt; [ ModuleIdentifier() ]
     *                           [ MandatoryPart() ]
     *                           ( CompliancePart() )*
     *                          )+ 
     * </PRE>
     */
    public void visit(ObjectInfoModuleCompliance n);

    /**
     * <PRE>
     * -> &lt;AGENT_CAPABILITIES_T&gt;
     * productReleasePart -> ProductReleasePart()
     * statusPart -> StatusPart()
     * descriptionPart -> DescriptionPart()
     * referencePart -> ReferencePart()
     * moduleCapabilitiesPart -> ( ModuleCapability() )*
     * </PRE>
     */
    public void visit(ObjectInfoAgentCapabilities n);

    /**
     * <PRE>
     * -> &lt;TRAP_TYPE_T&gt;
     * enterprisePart -> EnterprisePart()
     * variablesPart -> VariablesPart()
     * descriptionPart -> DescriptionPart()
     * number -> NumericValue()
     * </PRE>
     */
    public void visit(ObjectInfoTrapType n);

    /**
     * Grammar production:
     * <PRE>
     * nodeList -> &lt;REVISION_T&gt; &lt;UTC_TIME_T&gt; DescriptionPart()     
     * </PRE>
     * Syntaxtree :
     * <PRE>
     * time -> &lt;UTC_TIME_T&gt;
     * descr -> DescriptionPart()   
     * </PRE>
     */
    public void visit(Revision n);

    /**
     * <PRE>
     * -> &lt;STATUS_T&gt;
     * nodeChoice -> ( &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; )
     * </PRE>
     */
    public void visit(StatusPart n);

    /**
     * <PRE>
     * nodeChoice -> ( &lt;ACCESS_T&gt; | &lt;MAX_ACCESS_T&gt; | &lt;MIN_ACCESS_T&gt; )
     * nodeChoice1 -> ( &lt;NOT_ACCESSIBLE_T&gt; | &lt;ACCESSIBLE_FOR_NOTIFY_T&gt; | &lt;READ_ONLY_T&gt; | &lt;READ_WRITE_T&gt; | &lt;READ_CREATE_T&gt; | &lt;WRITE_ONLY_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; )
     * </PRE>
     */
    public void visit(AccessPart n);

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;MODULE_T&gt;
     *    [ ModuleIdentifier() ]          
     *    [ &lt;MANDATORY_GROUPS_T&gt;                         
     *      &lt;LEFT_BRACE_T&gt;               
     *      ObjectList()               
     *      &lt;RIGHT_BRACE_T&gt;
     *    ]
     *   ( CompliancePart() )*                 
     * </PRE>
     * syntax class variables:
     * <PRE>
     * module_id -> [ ModuleIdentifier() ]
     * mandatory_part -> [ ObjectList() ]                            
     * compliance_part -> ( CompliancePart() )*
     * </PRE>
     */
    public void visit(ModuleCompliance n);

    /** 
     * Grammar production:
     * <PRE>
     *  -> &lt;SUPPORTS_T&gt;
     * module_id -> ModuleIdentifier()
     * -> &lt;INCLUDES_T&gt;
     * -> &lt;LEFT_BRACE_T&gt;
     * object_list -> ObjectList()
     * -> &lt;RIGHT_BRACE_T&gt;
     * variation_part -> ( VariationPart() )*
     * </PRE>
     */
    public void visit(ModuleCapability n);

    /**
     * <PRE>
     * -> &lt;VARIATION_T&gt;
     * identifier -> ValueIdentifier()
     * syntaxPart -> SyntaxPart()
     * write_syntax -> [ &lt;WRITE_SYNTAX_T&gt; Types() ]
     * access -> [ AccessPart() ]
     * creation_requires -> [ &lt;CREATION_REQUIRES_T&gt; &lt;LEFT_BRACE_T&gt; ObjectList() &lt;RIGHT_BRACE_T&gt; ]
     * defValPart -> DefValPart()
     * descriptionPart -> DescriptionPart()
     * </PRE>
     */
    public void visit(VariationPart n);

    /**
     * <PRE>
     * -> &lt;SYNTAX_T&gt; Types()
     * type -> Types()
     * </PRE>
     */
    public void visit(SyntaxPart n);

    /**
     * <PRE>
     * -> &lt;WRITE_SYNTAX_T&gt; Types()
     * type -> Types()
     * </PRE>
     */
    public void visit(WriteSyntaxPart n);

    /**
     * <PRE>
     * -> &lt;GROUP_T&gt; ValueIdentifier() DescriptionPart()
     * identifier -> ValueIdentifier()
     * description -> DescriptionPart()
     * </PRE>
     */
    public void visit(ComplianceGroup n);

    /**
     * <PRE>
     * -> &lt;OBJECT_T&gt; ValueIdentifier()
     *       [ SyntaxPart() ]
     *       [ WriteSyntaxPart() ]
     *       [ AccessPart() ]
     *       DescriptionPart()
     * identifier -> ValueIdentifier()
     * syntax -> [ SyntaxPart() ]
     * write_syntax -> [ WriteSyntaxPart() ]
     * access -> [ AccessPart() ]
     * description -> DescriptionPart()
     * </PRE>
     */
    public void visit(ComplianceObject n);

    /**
     * <PRE>
     * type -> &lt;SEQUENCE_T&gt; &lt;LEFT_BRACE_T&gt; ValueIdentifier() Types() ( &lt;COMMA_T&gt; ValueIdentifier() Types() )* &lt;RIGHT_BRACE_T&gt;
     *       | &lt;SEQUENCE_T&gt; TypeIdentifier()
     *       | &lt;SEQUENCE_OF_T&gt; TypeIdentifier()
     *       | &lt;INTEGER_T&gt; [ RestrictionInteger() ]
     *       | &lt;INTEGER32_T&gt; [ RestrictionInteger() ]
     *       | &lt;UINTEGER32_T&gt; [ RestrictionInteger() ]
     *       | &lt;UNSIGNED32_T&gt; [ RestrictionInteger() ]
     *       | &lt;BITS_T&gt; [ RestrictionNamedNumberList() ]
     *       | &lt;BIT_STRING_T&gt; [ RestrictionNamedNumberList() ]
     *       | &lt;OCTET_STRING_T&gt; [ RestrictionSize() ]
     *       | &lt;OBJECT_IDENTIFIER_T&gt;
     *       | &lt;COUNTER_T&gt;
     *       | &lt;COUNTER32_T&gt;
     *       | &lt;COUNTER64_T&gt;
     *       | &lt;GAUGE_T&gt; [ RestrictionInteger() ]
     *       | &lt;GAUGE32_T&gt; [ RestrictionInteger() ]
     *       | &lt;TIMETICKS_T&gt;
     *       | &lt;OPAQUE_T&gt; [ RestrictionSize() ]
     *       | &lt;NSAP_ADDRESS_T&gt;
     *       | &lt;IP_ADDRESS_T&gt;
     *       | &lt;NETWORK_ADDRESS_T&gt;
     * </PRE>
     */
    public void visit(TypeSmi n);

    /**
     * <PRE>
     * identifier -> TypeIdentifier()
     * restriction -> [ Restriction() ]
     * </PRE>
     */
    public void visit(TypeIdentifier n);

    /**
     * <PRE> 
     * -> &lt;SEQUENCE_OF_T&gt; 
     * identifier -> TypeIdentifier()
     * </PRE>
     */
    public void visit(TypeSequenceOf n);
 
    /**
     * <PRE>
     * -> &lt;LEFT_PAREN_T&gt;
     * range -> Range()
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(RestrictionRange n);

    /**
     * <PRE>
     * -> &lt;LEFT_PAREN_T&gt;
     * -> &lt;SIZE_T&gt;
     * -> &lt;LEFT_PAREN_T&gt;
     * range -> Range()
     * -> &lt;RIGHT_PAREN_T&gt;
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(RestrictionSize n);

    /**
     * <PRE>
     * -> &lt;LEFT_BRACE_T&gt;
     *        NamedNumber() ( &lt;COMMA_T&gt; NamedNumber() )*
     *    &lt;RIGHT_BRACE_T&gt;
     * list -> ( NamedNumber() )+
     * </PRE>
     */
    public void visit(RestrictionNamedNumberList n);

    /**
     * <PRE>
     * nodeChoice -> RangeItem() ( &lt;OR_T&gt; RangeItem() )*
     * </PRE>
     */
    public void visit(RangeList n);

    /**
     * <PRE>
     * -> NumericValue()
     *    [ &lt;UNTIL_T&gt; NumericValue() ]
     * number1 -> NumericValue()
     * number2 -> NumericValue() -- NodeOptional --
     * </PRE>
     */
    public void visit(RangeItem n);

    /**
     * <PRE>
     * identifier -> ValueIdentifier()
     * -> &lt;LEFT_PAREN_T&gt;
     * number -> NumericValue()
     * -> &lt;RIGHT_PAREN_T&gt;
     * </PRE>
     */
    public void visit(NamedNumber n);

    /**
     * <PRE>
     * nodeChoice -> ( ModuleIdentifier() &lt;DOT_T&gt; &lt;TYPE_IDENTIFIER_T&gt; | &lt;TYPE_IDENTIFIER_T&gt; )
     * nodeChoice -> ( ModuleIdentifier() &lt;DOT_T&gt; ( &lt;VALUE_IDENTIFIER_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; | &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; ) | ( &lt;VALUE_IDENTIFIER_T&gt; | &lt;NOT_IMPLEMENTED_T&gt; | &lt;CURRENT_T&gt; | &lt;DEPRECATED_T&gt; | &lt;OBSOLETE_T&gt; | &lt;MANDATORY_T&gt; ) )
     * </PRE>
     */
    public void visit(Identifier n);

    /**
     * <PRE>
     * -> &lt;TYPE_IDENTIFIER_T&gt;
     * </PRE>
     */
    public void visit(ModuleIdentifier n);

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;AUGMENTS_T&gt;
     * -> &lt;LEFT_BRACE_T&gt;
     * identifier -> Identifier()
     * -> &lt;RIGHT_BRACE_T&gt; )
     * </PRE>
     */
    public void visit(IndexAugments n);

    /**
     * Grammar production:
     * <PRE>
     * -> &lt;IMPLIED_T&gt;
     * identifier -> Identifier()
     * </PRE>
     */
    public void visit(Index n);

    /**
     * <PRE>
     * list -> Index() ( &lt;COMMA_T&gt; Index() )*
     * </PRE>
     */
    public void visit(IndexList n);

    /**
     * <PRE>
     * -> &lt;LEFT_BRACE_T&gt;
     * oidValue -> OidValue()
     * nodeList -> ( OidValue() )+
     * -> &lt;RIGHT_BRACE_T&gt;
     * </PRE>
     */
    public void visit(AssignedValue n);

    /**
     * <PRE>
     * nodeChoice -> ValueIdentifier() [ &lt;LEFT_PAREN_T&gt; NumericValue() &lt;RIGHT_PAREN_T&gt; ]
     *       | NumericValue()
     * </PRE>
     */
    public void visit(OidValue n);

    /**
     * <PRE>
     * nodeChoice -> &lt;DEC_NUMBER_T&gt;
     *       | &lt;BIN_NUMBER_T&gt;
     *       | &lt;HEX_NUMBER_T&gt;
     * </PRE>
     */
    public void visit(NumericValue n);

    /**
     * <PRE>
     * -> &lt;DESCRIPTION_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(DescriptionPart n);

    /**
     * <PRE>
     * nodeOptional -> [ &lt;REFERENCE_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(ReferencePart n);

    /**
     * <PRE>
     * -> &lt;CONTACT_INFO_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(ContactInfoPart n);

    /**
     * <PRE>
     * -> &lt;ORGANIZATION_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(OrganizationPart n);

    /**
     * <PRE>
     * value -> ( &lt;DEFVAL_T&gt; &lt;LEFT_BRACE_T&gt;
     *               (  NumericValue() 
     *               | ValueIdentifier()
     *               | &lt;TEXT_T&gt;
     *               | BitValueList()
     *               | AssignedValue()
     *               )
     *            &lt;RIGHT_BRACE_T&gt; )?
     * </PRE>
     */
    public void visit(DefValPart n);

    /**
     * <PRE>
     * list -> ( ValueIdentifier() )*
     * </PRE>
     */
    public void visit(BitValueList n);

    /**
     * <PRE>
     * nodeOptional -> [ &lt;DISPLAY_HINT_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(DisplayHintPart n);

    /**
     * <PRE>
     * -> &lt;LAST_UPDATED_T&gt;
     * nodeToken1 -> &lt;UTC_TIME_T&gt;
     * </PRE>
     */
    public void visit(LastUpdatedPart n);

    /**
     * <PRE>
     * nodeOptional -> [ &lt;UNITS_T&gt; &lt;TEXT_T&gt; ]
     * </PRE>
     */
    public void visit(UnitsPart n);

    /**
     * <PRE>
     * -> &lt;PRODUCT_RELEASE_T&gt;
     * nodeToken1 -> &lt;TEXT_T&gt;
     * </PRE>
     */
    public void visit(ProductReleasePart n);

    /**
     * <PRE>
     * -> &lt;ENTERPRISE_T&gt;
     * identifier -> ValueIdentifier()
     * </PRE>
     */
    public void visit(EnterprisePart n);

    /**
     * Grammar production:
     * <PRE>
     * identifier -> ValueIdentifier()
     * type -> Types()
     * </PRE>
     */
    public void visit(ValueType n);

}

